set encoding=utf-8
set nocompatible
call plug#begin('~/.vim/plugged')

" Theme
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Syntax
Plug 'hdima/python-syntax'

" Productivity
Plug 'airblade/vim-gitgutter'
Plug 'christoomey/vim-tmux-navigator'
Plug 'easymotion/vim-easymotion'
Plug 'gregsexton/MatchTag'
Plug 'vim-scripts/matchit.zip'
Plug 'scrooloose/nerdtree'
Plug 'w0rp/ale'
Plug 'tpope/vim-fugitive'
Plug 'machakann/vim-sandwich'
Plug 'benmills/vimux'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'Valloric/YouCompleteMe'

call plug#end()

syntax on
set history=100
set autoread

filetype indent on


" Turn of wordwrap by default
set nowrap

" custom key mappings
let mapleader = "\<Space>"
let g:mapleader = "\<Space>"
nnoremap <leader>w :w<CR>

" GTFO
let g:gtfo#terminals = { 'unix': 'urxvt -cd' }

" Sandwich
let g:sandwich_no_default_key_mappings = 1
let g:operator_sandwich_no_default_key_mappings = 1
let g:textobj_sandwich_no_default_key_mappings = 1
runtime macros/sandwich/keymap/surround.vim

" YCM
let g:ycm_min_num_of_chars_for_completion = 3
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_autoclose_preview_window_after_completion = 1
map <leader>gd :YcmCompleter GoToDefinition<CR>
map <leader>gl :YcmCompleter GoToDeclaration<CR>


" NERDTree
let g:NERDTreeWinPos = "right"
let g:NERDTreeIgnore = ['\.pyc$','\.rpyc$', '__pycache__']
map <C-n> :NERDTreeToggle<CR>

" Trailing whitespace guide
set lcs=eol:¬,tab:»»,trail:∙
set list

" syntastic
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_python_checkers = ['flake8']

" Tab management
map <leader>tn :tabnew<CR>

" Easymotion
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1
nmap s <Plug>(easymotion-s)
map <leader>j <Plug>(easymotion-j)
map <leader>k <Plug>(easymotion-k)

" remove hl navigation
noremap h <NOP>
noremap l <NOP>

noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" buffer navigation
noremap <silent> <leader>] :bn<CR>
noremap <silent> <leader>[ :bp<CR>

" FZF
let g:fzf_action = {
      \ 'ctrl-x': 'split',
      \ 'ctrl-v': 'vsplit' }
let g:fzf_layout = { 'down': '40%' }
let g:fzf_launcher = 'urxvt -geometry 80x30 -e sh -c %s'
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

nnoremap <silent> <Leader><Leader> :Files<CR>
nnoremap <silent> <Leader><Enter> :Buffers<CR>
nnoremap <silent> <Leader>` :Marks<CR>
nnoremap <silent> <Leader>t :Ag<CR>
nnoremap <silent> <Leader>l :Lines<CR>

imap <c-x><c-j> <plug>(fzf-complete-file-ag)


" colorscheme
set bg=dark
colorscheme gruvbox


" airline
set laststatus=2
set noshowmode
let g:airline_powerline_fonts=1

" Code guide for more than 80 characters
set colorcolumn=100

" Line numbering
set number

" 1 tab == 2 spaces
" set smarttab
set tabstop=2
set shiftwidth=2

" Use spaces instead of tabs
set expandtab

" set autoindent
" set smartindent

" Disable backup
set nobackup
set nowb
set noswapfile

set hidden

set ignorecase
set smartcase
set hlsearch
set incsearch

set ruler
set magic

set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L
set guioptions-=e

" Clipboard
set clipboard=unnamedplus
