set encoding=utf-8
call plug#begin('~/.vim/plugged')

" Theme
Plug 'morhetz/gruvbox'
Plug 'chriskempson/base16-vim'
Plug 'itchyny/lightline.vim'

" Syntax
Plug 'hdima/python-syntax'

" Productivity
Plug 'airblade/vim-gitgutter'
Plug 'christoomey/vim-tmux-navigator'
Plug 'easymotion/vim-easymotion'
Plug 'gregsexton/MatchTag'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'Yggdroot/indentLine'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'


call plug#end()

syntax on
set history=100
set autoread

" Turn of wordwrap by default
set nowrap

" custom key mappings
let mapleader = ","
let g:mapleader = ","
map <silent><C-n> <Plug>NERDTreeTabsToggle<CR>

" NERDTree
let g:nerdtree_tabs_focus_on_files = 0
let g:NERDTreeWinPos = "right"
let g:NERDTreeIgnore = ['\.pyc$','\.rpyc$']

" indentLine
let g:indentLine_enabled = 0
let g:indentLine_leadingSpaceChar = '∙'
let g:indentLine_leadingSpaceEnabled = 1
set lcs=eol:¬,tab:»»,trail:∙
set list

" syntastic
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_python_checkers = ['flake8']

" Tab management
map <leader>tn :tabnew<CR>

" Easymotion
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1
nmap s <Plug>(easymotion-s)
map <leader>j <Plug>(easymotion-j)
map <leader>k <Plug>(easymotion-k)

" FZF
let g:fzf_action = {
      \ 'ctrl-t': 'tab split',
      \ 'ctrl-x': 'split',
      \ 'ctrl-v': 'vsplit' }

let g:fzf_layout = { 'down': '40%' }
let g:fzf_launcher = 'urxvt -geometry 80x30 -e sh -c %s'

nnoremap <silent> <C-p> :Files<CR>
nnoremap <silent> <C-b> :Buffers<CR>
nnoremap <silent> <C-t> :Ag<CR>

" paper color
set bg=dark
let base16colorspace=256
colorscheme base16-default-dark

set colorcolumn=80

" Line numbering
set number

" lightline
let g:lightline = {
      \ 'colorscheme': 'jellybeans',
      \ }
set laststatus=2
set noshowmode

" 1 tab == 2 spaces
" set smarttab
set tabstop=2
set shiftwidth=2

" Use spaces instead of tabs
set expandtab

set autoindent " Auto indent
set smartindent " Smart indent

" Disable backup
set nobackup
set nowb
set noswapfile

set hidden

set lazyredraw

set ignorecase
set smartcase
set hlsearch
set incsearch

set ruler
set magic

set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L
set guioptions-=e
