set encoding=utf-8
call plug#begin('~/.vim/plugged')

" Theme
Plug 'morhetz/gruvbox'

" Syntax
Plug 'sheerun/vim-polyglot'

" Productivity
Plug 'airblade/vim-gitgutter'
Plug 'bling/vim-airline'
Plug 'christoomey/vim-tmux-navigator'
Plug 'easymotion/vim-easymotion'
Plug 'gregsexton/MatchTag'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'Yggdroot/indentLine'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'xolox/vim-misc'
Plug 'xolox/vim-notes'


call plug#end()

syntax on
set history=100
set autoread

" Turn of wordwrap by default
set nowrap

" custom key mappings
let mapleader = ","
let g:mapleader = ","
map <silent><C-n> <Plug>NERDTreeTabsToggle<CR>

" NERDTree
let g:nerdtree_tabs_focus_on_files = 0
let g:NERDTreeWinPos = "right"
let g:NERDTreeIgnore = ['\.pyc$','\.rpyc$']

" indentLine
let g:indentLine_enabled = 0
let g:indentLine_leadingSpaceChar = '∙'
let g:indentLine_leadingSpaceEnabled = 1
set lcs=eol:¬,tab:»»,trail:∙
set list


" notes
let g:notes_directories  = ['~/Documents/Notes', '~/Dropbox/Notes']
let g:notes_conceal_code = 0
let g:notes_conceal_italic = 0
let g:notes_conceal_bold = 0

" syntastic
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_python_checkers = ['flake8']

" Tab management
map <leader>tn :tabnew<CR>

" Easymotion
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1
nmap <s> <Plug>(easymotion-s)
map <leader>j <Plug>(easymotion-j)
map <leader>k <Plug>(easymotion-k)

" FZF 
let g:fzf_action = {
      \ 'ctrl-t': 'tab split',
      \ 'ctrl-x': 'split',
      \ 'ctrl-v': 'vsplit' }

let g:fzf_layout = { 'down': '40%' }

nnoremap <silent> <C-p> :Files<CR>
nnoremap <silent> <C-b> :Buffers<CR>
nnoremap <silent> <C-t> :Ag<CR>

" gruvbox
let g:gruvbox_invert_selection = 0
let g:gruvbox_contrast_dark = "hard"
let g:gruvbox_contrast_light = "medium"
set bg=dark
colorscheme gruvbox

" airline
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_buffers = 0
set laststatus=2
set noshowmode

set colorcolumn=80

" Line numbering
set number

" 1 tab == 2 spaces
" set smarttab
set tabstop=2
set shiftwidth=2

" Use spaces instead of tabs
set expandtab

set autoindent " Auto indent
set smartindent " Smart indent

" Disable backup
set nobackup
set nowb
set noswapfile

set hidden

set lazyredraw

set ignorecase
set smartcase
set hlsearch
set incsearch

set ruler
set magic
